title: J M Kathir
logo: assets/profile pic.png
description: 
Researcher|Data Analyst|Buisness Analyst 
[Download CV](https://github.com/user-attachments/files/16600631/Data.Analyst.CV.pdf)
show_downloads: false
theme: jekyll-theme-minimal
