title: J M Kathir
logo: assets/profile pic.png
description: Researcher|Data Analyst|Buisness Analyst ![LinkedIn](https://www.linkedin.com/in/kathir-jm/) |  ![kathirrodriguez@gmail,com](kathirrodriguez@gmail.com) | ![Github](https://github.com/Kathirrodri17/Portfolio-Projects/blob/main/README.md)
show_downloads: false
theme: jekyll-theme-minimal
